module.exports = {
  'dwarf/ajfaraday/baby_steps': require('./clients/dwarf/ajfaraday/baby_steps.js'),
  'dwarf/default/keep_away': require('./clients/dwarf/default/keep_away.js'),
  'dwarf/default/lucky_7': require('./clients/dwarf/default/lucky_7.js'),
  'dwarf/shaggy/baby_steps_duplicate': require('./clients/dwarf/shaggy/baby_steps_duplicate.js'),
  'dwarf/template': require('./clients/dwarf/template.js'),
  'inert/dummy': require('./clients/inert/dummy.js'),
  'inert/dummy_two': require('./clients/inert/dummy_two.js'),
  'inert/manual': require('./clients/inert/manual.js'),
  'troll/ajfaraday/_imported': require('./clients/troll/ajfaraday/_imported.js'),
  'troll/default/last_move': require('./clients/troll/default/last_move.js'),
  'troll/default/spread_out': require('./clients/troll/default/spread_out.js'),
  'troll/shaggy/_imported_duplicate': require('./clients/troll/shaggy/_imported_duplicate.js'),
  'troll/template': require('./clients/troll/template.js'),
};